### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by johndburger** [dribnet/lfw_fuel#1]
If I clone the repo and run the example from the lfw_fuel directory, I get this error:

```
Traceback (most recent call last):
  File "example/run-lfw.py", line 17, in <module>
    from lfw_fuel import low
  File "build/bdist.linux-x86_64/egg/lfw_fuel/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/lfw_fuel/lfw.py", line 214, in <module>
  File "/home/john/.local/lib/python2.7/site-packages/kerosene/datasets/dataset.py", line 11, in <module>
    initial_fuel_config_path = fuel.config.data_path
  File "/usr/local/lib/python2.7/dist-packages/fuel/config_parser.py", line 150, in __getattr__
    "provided: {}.".format(key))
fuel.exceptions.ConfigurationError: Configuration not set and no default provided: data_path.
```

I can get past this by running it thusly:

```
FUEL_DATA_PATH=$PWD/fueldata python example/run-lfw.py
```

but then I get this error:

```
  File "example/run-lfw.py", line 38, in <module>
    (X_train, y_train), (X_test, y_test) = lfw.load_data("deepfunneled")
  File "/home/john/dev/lfw_fuel/lfw_fuel/lfw.py", line 233, in load_data
    return dataset.load_data(sets, sources, fuel_dir);
  File "/home/john/.local/lib/python2.7/site-packages/kerosene/datasets/dataset.py", line 78, in load_data
    datasets = self.build_data(sets, sources)
  File "/home/john/dev/lfw_fuel/lfw_fuel/lfw.py", line 228, in build_data
    return map(lambda s: LFW(which_sets=[s], sources=sources), sets)
  File "/home/john/dev/lfw_fuel/lfw_fuel/lfw.py", line 228, in <lambda>
    return map(lambda s: LFW(which_sets=[s], sources=sources), sets)
  File "/home/john/dev/lfw_fuel/lfw_fuel/lfw.py", line 208, in __init__
    which_sets=which_sets, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 186, in __init__
    self._parse_dataset_info()
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 202, in _parse_dataset_info
    self._out_of_memory_open()
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 505, in _out_of_memory_open
    name=self.path, mode="r", driver=self.driver)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 260, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 89, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-snmJ8l/h5py/h5py/_objects.c:2574)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-snmJ8l/h5py/h5py/_objects.c:2533)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-build-snmJ8l/h5py/h5py/h5f.c:1811)
IOError: Unable to open file (Unable to find a valid file signature)
```

It seems to think the data is already downloaded. Any suggestions? Thanks.

**Comment by dribnet** [comment]
Hi - thanks for the bug report. The upstream kerosene library should download the hdf5 data to the cache subdirectory at `~/.kerosene/datasets`. It might be that a download started and then was aborted - a similar issue was reported in dribnet/kerosene#1. As an extreme measure you can delete the local cache:

``` bash
rm -Rf ~/.kerosene/datasets
```

and then try again. I'll look into this more tonight, or feel free to try this workaround in the meantime.

**Comment by johndburger** [comment]
That's exactly what was wrong. I had checked under ~/.fuel thinking it was something like that, but I'm still learning about the fuel/kerosene stack. Thanks very much.

-- JB

**Comment by dribnet** [comment]
Great - I'll fix this upstream in kerosene with a more robust downloader in the next version. Let me know if you find anything else amiss.

**Comment by wiem9** [comment]
I cloned the rep and I run it on spyder and it shows me this error ModuleNotFoundError: No module named 'lfw_fuel'
